# vim: set filetype=sh :

#****************
# Shell options
#****************

# Use Vi, not Emacs, style editing
set editing-mode vi
set keymap vi

# vi mode in bash
set -o vi

# Make Tab autocomplete regardless of filename case
set completion-ignore-case on

# List all matches in case multiple possible completions are possible
set show-all-if-ambiguous on

# Immediately add a trailing slash when autocompleting symlinks to directories
set mark-symlinked-directories on

# Do not autocomplete hidden files unless the pattern explicitly begins with a dot
set match-hidden-files off

# Show all autocomplete results at once
set page-completions off

# If there are more than 200 possible completions for a word, ask to show them all
set completion-query-items 200

# Show extra file information when completing, like `ls -F` does
set visible-stats on

# Be more intelligent when autocompleting by also looking at the text after
# the cursor. For example, when the current line is "cd ~/src/mozil", and
# the cursor is on the "z", pressing Tab will not autocomplete it to "cd
# ~/src/mozillail", but to "cd ~/src/mozilla". (This is supported by the
# Readline used by Bash 4.)
set skip-completed-text on

# Allow UTF-8 input and output, instead of showing stuff like $'\0123\0456'
set input-meta on
set output-meta on
set convert-meta off

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob

# Append to the Bash history file, rather than overwriting it
shopt -s histappend

# Autocorrect typos in path names when using `cd`
shopt -s cdspell

shopt -s checkwinsize

# Set the correct terminal size
eval $(/usr/bin/resize)

#***************
# Bash Exports
#***************

# Set the terminal type to xterm-256color
export TERM=xterm-256color

# Make vim the default editor
export EDITOR="vim"

# Larger bash history
export HISTSIZE=2000
export HISTFILESIZE=$HISTSIZE
export HISTCONTROL=ignoredups
# Make some commands not show up in history
export HISTIGNORE="ls:cd:cd -:pwd:exit:date:* --help"

# Prefer US English and use UTF-8
export LANG="en_US"
export LC_ALL="en_US.UTF-8"

# Highlight section titles in manual pages
export LESS_TERMCAP_md="$ORANGE"

# Don’t clear the screen after quitting a manual page
export MANPAGER="less -X"

# Always enable colored `grep` output
export GREP_OPTIONS="--color=auto"

# Fancy ls colors
export CLICOLOR='Yes'
export LSCOLORS='ExGxCxDxBxegedabagacad'

# Prevent 'less' from
export LESS="-i -R"
export LESSHISTFILE='/dev/null'
export LESSHISTSIZE=0

# git prompt related environment variables
export GIT_PS1_SHOWDIRTYSTATE='yes'
export GIT_PS1_SHOWSTASHSTATE='yes'
export GIT_PS1_SHOWUNTRACKEDFILES='yes'

#***************
# Bash Aliases
#***************

# List all files colorized in long format
alias l="ls -lF --color"

# List all files colorized in long format, including dot files
alias la="ls -laF --color"

# List only directories
alias lsd="ls -lF --color | grep --color=never '^d'"

# Always use color output for `ls`
alias ls="command ls --color"

# List and kill off tmux sessions
alias tls='/usr/bin/tmux ls'
alias tks='/usr/bin/tmux kill-session -t '

# Alias git to g
alias g="git"

# APG alias for friendly passwords
alias apgf='apg -a 0 -n 10 -m 10 -t -E lI10O -M NCSL'

# Docker related aliases
alias drm="docker rm -f"
alias dps="docker ps"

# Command line weather
alias weather="curl http://wttr.in/toronto"

# System Update
alias yoloupdate="sudo apt-get update && sudo apt-get -y dist-upgrade && sudo apt-get clean && sudo apt-get autoremove -y --purge"



#************
# GPG agent
#************

if [ -f "${HOME}/.gnupg/gpg-agent-info" ]; then
  . "${HOME}/.gnupg/gpg-agent-info"
  export GPG_AGENT_INFO
  export SSH_AUTH_SOCK
fi

#*****************
# Tab Completion
#*****************

# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
if [ -e "$HOME/.ssh/config" ]; then
  complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2 | tr ' ' '\n')" scp sftp ssh cs
fi

# If possible, add tab completion for many more commands
if [ -f /etc/bash_completion ]; then
  source /etc/bash_completion
fi

#**************
# Bash Prompt
#**************

function __prompt_command() {
  local EXIT="$?"
  PS1=""

  # Set the terminal title
  echo -ne "\033]0;${HOSTNAME}\007"

  local RED="\[$(tput setaf 1)\]"
  local GREEN="\[$(tput setaf 2)\]"
  local YELLOW="\[$(tput setaf 3)\]"
  local BLUE="\[$(tput setaf 4)\]"
  local MAGENTA="\[$(tput setaf 5)\]"
  local CYAN="\[$(tput setaf 6)\]"
  local WHITE="\[$(tput setaf 7)\]"
  local BOLD="\[$(tput bold)\]"
  local UNDERLINE="\[$(tput sgr 0 1)\]"
  local RESET="\[$(tput sgr0)\]"
  local PROMPTCOL="${YELLOW}"

  if [ -f '/.dockerenv' ]; then
    # We're inside a docker environment
    PS1+="\n${GREEN}"
  elif [ `id -u` == 0 ]; then
    # Bright red prompt if root
    PS1+="\n${RED}"
  else
    PS1+="\n${PROMPTCOL}"
  fi

  # Second line of bash prompt
  if [ -f '/.dockerinit' ]; then
    # We're inside a docker environment
    PS1+="[docker-\H: \t]${RESET}${BLUE}$(__git_ps1 ' [%s]')${RESET}${PROMPTCOL} \w${RESET}\n"
  else
    PS1+="[\H: \t]${RESET}${BLUE}$(__git_ps1 ' [%s]')${RESET}${PROMPTCOL} \w${RESET}\n"
  fi

  # Print out the last exit code, if it wasn't zero
  if [ $EXIT != 0 ]; then
    PS1+="${RED}[${EXIT}]${RESET} "
  fi

  # Finally print out a $ or #, depending on uid
  PS1+="${PROMPTCOL}\\$ ${RESET}"
}

export PROMPT_COMMAND=__prompt_command  # Func to gen PS1 after CMDs

#*******************
# Helper Functions
#*******************

# Simple calculator
function calc() {
  local result=""
  result="$(printf "scale=10;$*\n" | bc --mathlib | tr -d '\\\n')"
  #                       └─ default (when `--mathlib` is used) is 20
  #
  if [[ "$result" == *.* ]]; then
    # improve the output for decimal numbers
    printf "$result" |
    sed -e 's/^\./0./'        `# add "0" for cases like ".5"` \
        -e 's/^-\./-0./'      `# add "0" for cases like "-.5"`\
        -e 's/0*$//;s/\.$//'   # remove trailing zeros
  else
    printf "$result"
  fi
  printf "\n"
}

# Determine size of a file or total size of a directory
function fs() {
  if du -b /dev/null > /dev/null 2>&1; then
    local arg=-sbh
  else
    local arg=-sh
  fi
  if [[ -n "$@" ]]; then
    du $arg -- "$@"
  else
    du $arg .[^.]* *
  fi
}

# `tre` is a shorthand for `tree` with hidden files and color enabled, ignoring
# the `.git` directory, listing directories first. The output gets piped into
# `less` with options to preserve color and line numbers, unless the output is
# small enough for one screen.
function tre() {
  tree -aC -I '.git|node_modules|bower_components' --dirsfirst "$@" | less -FRNX
}

# Function to clean up docker containers
function drma() {
  local dps=$(docker ps -aq)
  if [ -n "$dps" ]; then
    docker rm -f $dps
  fi

  # Delete all untagged docker images
  local untagged=$(docker images | grep "^<none>" | awk "{print $3}")
  if [ -n "$untagged" ]; then
    docker rmi -f $untagged
  fi
}

# Bash function to attach to, or spin up a new (named) docker container
function sink () {
  local boxname=$1
  local dockerargs=$2
  local workdir="/home/marvin"

  if [ -z "$boxname" ]; then
    echo "usage: sink <box name> [extra docker args]"
    echo "e.g. sink tidycat-ui \"-p 4200:4200\""
    return 1
  fi

  if [ -e "${HOME}/projects/${boxname}" ]; then
    workdir="/home/marvin/projects/${boxname}"
  fi

  local dockerid=$(docker ps -aq --filter=name=$boxname)
  if [ "$dockerid" != "" ]; then
    echo "Attaching to existing docker container ${dockerid}"
  else
    echo "Creating new docker container"
    dockerid=$(docker run -dit \
      -e "HOSTNAME=${boxname}" \
      --name $boxname \
      --hostname ${boxname} \
      -v /home/marvin:/var/shared \
      -v $(dirname $SSH_AUTH_SOCK):$(dirname $SSH_AUTH_SOCK) \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -e SSH_AUTH_SOCK=$SSH_AUTH_SOCK \
      $dockerargs \
      -w $workdir \
      "quay.io/marvin/kitchensink")
  fi
  docker exec -it $dockerid /bin/bash
}

# Delete an EC2 AMI & corresponding snapshot
function delete-ec2-ami() {
  local ami_id=$1

  if [ -z "$ami_id" ]; then
    echo "usage: delete-ec2-ami <ami_id>"
    return 1
  fi

  local snap_id=$(aws ec2 describe-snapshots --filters Name=description,Values="*${ami_id}*" | python -c 'import sys, json; print json.load(sys.stdin)["Snapshots"][0]["SnapshotId"]')

  aws ec2 deregister-image --image-id ${ami_id}
  aws ec2 delete-snapshot --snapshot-id ${snap_id}
}

# Mirror my laptop display to the connected monitor (i.e. presentation mode!)
function presentation-mode() {
  local display=$(xrandr | grep -v LVDS1 | grep " connected" | cut -d" " -f1)
  xrandr --output ${display} --same-as LVDS1
}

# Start my irssi im container
function im() {
  docker run -it \
    -e TERM \
    -u $(id -u):$(id -g) \
    --read-only \
    -v $HOME/.irssi:/home/user/.irssi \
    -v /etc/localtime:/etc/localtime \
    irssi \
    irssi --config=/home/user/.irssi/config-im --home=/home/user/.irssi
}

# Launch a containerized gimp
function docker-gimp() {
  xhost local:root
  docker run -it \
    --rm \
    -v /etc/localtime:/etc/localtime:ro \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e DISPLAY=$DISPLAY \
    -v ${HOME}/crap:/root/Pictures \
    --name gimp \
    jess/gimp
}

# Launch a containerized chrome
function docker-chrome() {
  xhost local:root
  docker run -it \
    --rm \
    --net host \
    --cpuset-cpus 0 \
    --memory 512mb \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e DISPLAY=$DISPLAY \
    -v $HOME/crap:/root/Downloads \
    --device /dev/snd \
    --name chrome \
    jess/chrome
}

# Launch a containerized inkscape
function docker-inkscape() {
  xhost local:root
  docker run -it \
    --rm \
    -u inkscaper \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -v $HOME/.Xauthority:/home/inkscaper/.Xauthority \
    -e DISPLAY=$DISPLAY \
    -v $HOME/crap:/home/inkscaper/Downloads \
    --name inkscape \
    rasch/inkscape
}

# Launch a containerized bittorrent client
function docker-bittorrent() {
  echo "http://docktorrent:p@ssw0rd@`docker inspect --format '{{ .NetworkSettings.IPAddress }}' bittorrent`"
  echo "May need to futz with the $HOME/bittorrent permissions a bit"
  mkdir -p ${HOME}/bittorrent
  rm -f ${HOME}/bittorrent/.session/rtorrent.lock
  docker rm -f bittorrent || true
  docker run -it \
    --rm \
    -p 45566:45566 \
    -p 9527:9527/udp \
    --dns 8.8.8.8 \
    -v $HOME/bittorrent:/rtorrent \
    -e UPLOAD_RATE=1024 \
    --name bittorrent \
    kfei/docktorrent
}

# Launch a containerized vlc client
function docker-vlc() {
  mkdir -p ${HOME}/bittorrent
  docker run -it \
    --rm \
    -v $HOME/bittorrent:/home/vlc/Documents:rw \
    -v /dev/snd:/dev/snd --privileged \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e uid=$(id -u) \
    -e gid=$(id -g) \
    -e DISPLAY=unix$DISPLAY \
    --name vlc \
    chrisdaish/vlc
}

# Launch a containerized letsencrypt client
function docker-letsencrypt() {
  docker run -it \
    --rm \
    --name letsencrypt \
    -v "${HOME}/Dropbox/lets-encrypt/etc:/etc/letsencrypt" \
    -v "${HOME}/Dropbox/lets-encrypt/lib:/var/lib/letsencrypt" \
    quay.io/letsencrypt/letsencrypt:latest \
    -a manual \
    --verbose \
    auth
  sudo chown -R marvin: ${HOME}/Dropbox/lets-encrypt
}

function adiff() {
  local commit="$1"
  local file="$2"
  local vault_password_file="$3"

  if [ -z "$commit" -o -z "$file" ]; then
    echo "usage: adiff <commit> <file> [vault_password_file]"
    return 1
  fi

  if [ -z "$vault_password_file" ]; then
    vault_password_file=vault_pass.py
  fi

  diff -u \
    <( ansible-vault --vault-password-file="${vault_password_file}" view <( git show "${commit}^":"${file}" )) \
    <( ansible-vault --vault-password-file="${vault_password_file}" view <( git show "${commit}":"${file}" ))
}

# Determine size of a remote file via a HEAD request
function rfs() {
  local url="$1"

  if [ -z "$url" ]; then
    echo "usage: rfs <url>"
    return 1
  fi

  curl -sIL "$url" | grep Content-Length | sed 's/[^0-9]//g' | numfmt --to=si
}
